server:
  port: ${SERVER_PORT:8012}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_balance_limit}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST_IP:localhost}:${SERVER_PORT:8012}/eureka

logging:
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS XXX'
  level:
    root: INFO
    com:
      example.example.checkloanbalanceandlimitservice: DEBUG
  file:
    name: ${LOG_PATH:/checkloanbalanceandlimitservice/logs/}${LOGFILE:today.log}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:/checkloanbalanceandlimitservice/logs/}%d{ddMMyyyy}.%i.log
      max-history: 60
      max-file-size: 800MB